// Real Spanish municipalities for the programmatic local-SEO engine (locations.js).
// Verified town + province pairs. Expand with more REAL municipalities only —
// never invent places to inflate the count (that is doorway/thin-content spam).
module.exports = [
  { slug: 'noia', name: 'Noia', province: 'A Coruña' },
  { slug: 'betanzos', name: 'Betanzos', province: 'A Coruña' },
  { slug: 'sarria', name: 'Sarria', province: 'Lugo' },
  { slug: 'viveiro', name: 'Viveiro', province: 'Lugo' },
  { slug: 'ribadeo', name: 'Ribadeo', province: 'Lugo' },
  { slug: 'cangas-del-narcea', name: 'Cangas del Narcea', province: 'Asturias' },
  { slug: 'llanes', name: 'Llanes', province: 'Asturias' },
  { slug: 'grado', name: 'Grado', province: 'Asturias' },
  { slug: 'pravia', name: 'Pravia', province: 'Asturias' },
  { slug: 'reinosa', name: 'Reinosa', province: 'Cantabria' },
  { slug: 'santona', name: 'Santoña', province: 'Cantabria' },
  { slug: 'comillas', name: 'Comillas', province: 'Cantabria' },
  { slug: 'gernika-lumo', name: 'Gernika-Lumo', province: 'Vizcaya' },
  { slug: 'bermeo', name: 'Bermeo', province: 'Vizcaya' },
  { slug: 'tolosa', name: 'Tolosa', province: 'Guipúzcoa' },
  { slug: 'laudio-llodio', name: 'Laudio/Llodio', province: 'Álava' },
  { slug: 'amurrio', name: 'Amurrio', province: 'Álava' },
  { slug: 'estella-lizarra', name: 'Estella-Lizarra', province: 'Navarra' },
  { slug: 'tafalla', name: 'Tafalla', province: 'Navarra' },
  { slug: 'sanguesa', name: 'Sangüesa', province: 'Navarra' },
  { slug: 'haro', name: 'Haro', province: 'La Rioja' },
  { slug: 'santo-domingo-de-la-calzada', name: 'Santo Domingo de la Calzada', province: 'La Rioja' },
  { slug: 'najera', name: 'Nájera', province: 'La Rioja' },
  { slug: 'jaca', name: 'Jaca', province: 'Huesca' },
  { slug: 'barbastro', name: 'Barbastro', province: 'Huesca' },
  { slug: 'alcaniz', name: 'Alcañiz', province: 'Teruel' },
  { slug: 'andorra', name: 'Andorra', province: 'Teruel' },
  { slug: 'calatayud', name: 'Calatayud', province: 'Zaragoza' },
  { slug: 'banyoles', name: 'Banyoles', province: 'Girona' },
  { slug: 'la-bisbal-d-emporda', name: "La Bisbal d'Empordà", province: 'Girona' },
  { slug: 'tarrega', name: 'Tàrrega', province: 'Lleida' },
  { slug: 'cervera', name: 'Cervera', province: 'Lleida' },
  { slug: 'mollerussa', name: 'Mollerussa', province: 'Lleida' },
  { slug: 'valls', name: 'Valls', province: 'Tarragona' },
  { slug: 'montblanc', name: 'Montblanc', province: 'Tarragona' },
  { slug: 'el-catllar', name: 'El Catllar', province: 'Tarragona' },
  { slug: 'morella', name: 'Morella', province: 'Castellón' },
  { slug: 'segorbe', name: 'Segorbe', province: 'Castellón' },
  { slug: 'onda', name: 'Onda', province: 'Castellón' },
  { slug: 'requena', name: 'Requena', province: 'Valencia' },
  { slug: 'ayora', name: 'Ayora', province: 'Valencia' },
  { slug: 'cocentaina', name: 'Cocentaina', province: 'Alicante' },
  { slug: 'muro-de-alcoy', name: 'Muro de Alcoy', province: 'Alicante' },
  { slug: 'pego', name: 'Pego', province: 'Alicante' },
  { slug: 'cehegin', name: 'Cehegín', province: 'Murcia' },
  { slug: 'mula', name: 'Mula', province: 'Murcia' },
  { slug: 'bullas', name: 'Bullas', province: 'Murcia' },
  { slug: 'abaran', name: 'Abarán', province: 'Murcia' },
  { slug: 'calasparra', name: 'Calasparra', province: 'Murcia' },
  { slug: 'fortuna', name: 'Fortuna', province: 'Murcia' },
  { slug: 'pollenca', name: 'Pollença', province: 'Islas Baleares' },
  { slug: 'soller', name: 'Sóller', province: 'Islas Baleares' },
  { slug: 'arta', name: 'Artà', province: 'Islas Baleares' },
  { slug: 'felanitx', name: 'Felanitx', province: 'Islas Baleares' },
  { slug: 'ferreries', name: 'Ferreries', province: 'Islas Baleares' },
  { slug: 'santanyi', name: 'Santanyí', province: 'Islas Baleares' },
  { slug: 'cazalla-de-la-sierra', name: 'Cazalla de la Sierra', province: 'Sevilla' },
  { slug: 'estepa', name: 'Estepa', province: 'Sevilla' },
  { slug: 'grazalema', name: 'Grazalema', province: 'Cádiz' },
  { slug: 'vejer-de-la-frontera', name: 'Vejer de la Frontera', province: 'Cádiz' },
  { slug: 'olvera', name: 'Olvera', province: 'Cádiz' },
  { slug: 'iznajar', name: 'Iznájar', province: 'Córdoba' },
  { slug: 'alhama-de-granada', name: 'Alhama de Granada', province: 'Granada' },
  { slug: 'montefrio', name: 'Montefrío', province: 'Granada' },
  { slug: 'salobrena', name: 'Salobreña', province: 'Granada' },
  { slug: 'aracena', name: 'Aracena', province: 'Huelva' },
  { slug: 'cortegana', name: 'Cortegana', province: 'Huelva' },
  { slug: 'cazorla', name: 'Cazorla', province: 'Jaén' },
  { slug: 'frigiliana', name: 'Frigiliana', province: 'Málaga' },
  { slug: 'competa', name: 'Cómpeta', province: 'Málaga' },
  { slug: 'mojacar', name: 'Mojácar', province: 'Almería' },
  { slug: 'velez-rubio', name: 'Vélez-Rubio', province: 'Almería' },
  { slug: 'zafra', name: 'Zafra', province: 'Badajoz' },
  { slug: 'jerez-de-los-caballeros', name: 'Jerez de los Caballeros', province: 'Badajoz' },
  { slug: 'olivenza', name: 'Olivenza', province: 'Badajoz' },
  { slug: 'trujillo', name: 'Trujillo', province: 'Cáceres' },
  { slug: 'hervas', name: 'Hervás', province: 'Cáceres' },
  { slug: 'jarandilla-de-la-vera', name: 'Jarandilla de la Vera', province: 'Cáceres' },
  { slug: 'tegueste', name: 'Tegueste', province: 'Santa Cruz de Tenerife' },
  { slug: 'garachico', name: 'Garachico', province: 'Santa Cruz de Tenerife' },
  { slug: 'tazacorte', name: 'Tazacorte', province: 'Santa Cruz de Tenerife' },
  { slug: 'teror', name: 'Teror', province: 'Las Palmas' },
  { slug: 'firgas', name: 'Firgas', province: 'Las Palmas' },
  { slug: 'valleseco', name: 'Valleseco', province: 'Las Palmas' },
  { slug: 'chinchon', name: 'Chinchón', province: 'Madrid' },
  { slug: 'colmenar-de-oreja', name: 'Colmenar de Oreja', province: 'Madrid' },
  { slug: 'villa-del-prado', name: 'Villa del Prado', province: 'Madrid' },
  { slug: 'cadalso-de-los-vidrios', name: 'Cadalso de los Vidrios', province: 'Madrid' },
  { slug: 'torrijos', name: 'Torrijos', province: 'Toledo' },
  { slug: 'ocana', name: 'Ocaña', province: 'Toledo' },
  { slug: 'sonseca', name: 'Sonseca', province: 'Toledo' },
  { slug: 'quintanar-de-la-orden', name: 'Quintanar de la Orden', province: 'Toledo' },
  { slug: 'tarancon', name: 'Tarancón', province: 'Cuenca' },
  { slug: 'mota-del-cuervo', name: 'Mota del Cuervo', province: 'Cuenca' },
  { slug: 'siguenza', name: 'Sigüenza', province: 'Guadalajara' },
  { slug: 'manzanares', name: 'Manzanares', province: 'Ciudad Real' },
  { slug: 'la-roda', name: 'La Roda', province: 'Albacete' },
  { slug: 'arevalo', name: 'Arévalo', province: 'Ávila' },
  { slug: 'cebreros', name: 'Cebreros', province: 'Ávila' },
  { slug: 'el-barco-de-avila', name: 'El Barco de Ávila', province: 'Ávila' },
];
